name: Math Calculation Workflow

on: [push]

jobs:
  calculate-sum:
    runs-on: ubuntu-latest
    outputs:
      sum: ${{ steps.sum-output.outputs.sum }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Calculate sum
      id: sum-output
      run: |
        num1=3
        num2=7
        sum=$((num1 + num2))
        echo "Sum of $num1 and $num2 is $sum"
        echo "::set-output name=sum::$sum"

  calculate-square:
    runs-on: ubuntu-latest
    needs: calculate-sum
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Calculate square
      run: |
        sum=${{ needs.calculate-sum.outputs.sum }}
        square=$((sum * sum))
        echo "Square of $sum is $square"
